# -*- coding: utf-8 -*-
"""task-3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10-j-0z1HJODCSxr-w6MzT7TcnmtDr50i
"""

#task 3
def function(inp, out):
    coin, value = [int(x) for x in inp.readline().split()]
    coin_list = [int(x) for x in inp.readline().split()]
    value_list = [value + 1] * (value + 1)
    value_list[0] = 0

    for i in range(1, value + 1):
        for j in range(len(coin_list)):
            if(i - coin_list[j] >= 0):
                value_list[i] = min(value_list[i], 1 + value_list[i - coin_list[j]])

    if(value_list[value] == value + 1):
        print(-1, file = out)

    else:
        print(value_list[value], file = out)

    inp.close()
    out.close()

inp = open("/content/input3.txt", "r")
out = open("/content/output3.txt", "w")
function(inp, out)