# -*- coding: utf-8 -*-
"""task-2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p2vMSrzdea3VNnFX4j7GqvMIAf9Fw-Jf
"""

#task 2
def function(inp, out):
    n = int(inp.readline()) + 1
    arr = [None] * (n+1)
    print(fibo(n, arr), file = out)

    inp.close()
    out.close()

def fibo(n, arr):
    if(n == 0 or n == 1):
        arr[n] = n
        return arr[n]

    if(arr[n] != None):
        return arr[n]

    arr[n] = fibo(n - 1, arr) + fibo(n - 2, arr)
    return arr[n]


inp = open("/content/input2.txt", "r")
out = open("/content/output2.txt", "w")
function(inp, out)