# -*- coding: utf-8 -*-
"""task-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oP-NYS_Iyy6utXxRzeoVy-17_fm6cdA5
"""

#task1
def margesort(arr,combo):
  if len(arr) <=1:
    return arr
  mid= len(arr)//2
  a= margesort(arr[:mid],combo)
  b=margesort(arr[mid:],combo)
  result=[]
  i=j=0
  while i< len(a) and j< len(b):
    if a[i]<= b[j]:
      result.append(a[i])
      i+=1
    else:
      result.append(b[j])
      combo[arr.index(b[j])]+= len(a)-i
      j+=1
    #print(combo)
  result+=a[i:]
  result+=b[j:]
  return result

inp=open("/content/input1.txt","r")
out=open("/content/output1.txt","w")
n= int(inp.readline())
arr=[int(x) for x in inp.readline().split()]
combo=[0]*n
margesort(arr,combo)
#print(combo)
r= str(sum(combo))
#print(r)
out.write(r)
inp.close()
out.close()

