# -*- coding: utf-8 -*-
"""task-4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iWp8WBob1ySsd1LyjSTC3Uxh2bbwO7sM
"""

#task4
def Partition(arr, start, end):
    pivot = arr[end]
    idx = start - 1

    for i in range(start, end):
        if arr[i] <= pivot:
            idx += 1
            arr[idx], arr[i] = arr[i], arr[idx]

    arr[idx + 1], arr[end] = arr[end], arr[idx + 1]

    return idx + 1

def find_kth_smallest(arr,k):
    sml = 0
    lrg = len(arr) - 1

    while True:
        pivot = Partition(arr, sml, lrg)
        if pivot == k - 1:
            return arr[pivot]
        elif pivot > k - 1:
            lrg = pivot - 1
        else:
            sml = pivot + 1
inp = open('/content/input4.txt','r')
out = open('/content/output4.txt','w')
length = int(inp.readline())
arr = [int(x) for x in inp.readline().split()]
test = int(inp.readline())

for i in range(test):
    k_val = int(inp.readline())
    result = str(find_kth_smallest(arr, k_val))
    print(result)
    out.write(result + '\n')
inp.close()
out.close()