# -*- coding: utf-8 -*-
"""task-2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FrA44bW-QkKNhhA6Ydy1SRIObo1zCg1V
"""

#task2
def function(keys,values):
  lst=[]
  i = 0
  j = i + 1
  while i < len(keys) - 1:
    x = keys[i] + values[j]
    lst.append(x)

    j += 1
    if j >= len(values):
        i += 1
        j = i + 1
  return lst

inp = open("/content/input2.txt", "r")
out= open("/content/output2.txt", "w")
dic={}
r=int(inp.readline())
arr = [int(x) for x in inp.readline().split()]
for i in range(r):
  dic[arr[i]]=(arr[i])**2
keys = list(dic.keys())
values = list(dic.values())
a=(function(keys,values))
#print(a)
m=max(a)
print(a)
out.write(str(m))
inp.close()
out.close()