# -*- coding: utf-8 -*-
"""task1a.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TnOlVb6DBF3ZTnPTBGGjIJwHtQVceE-A
"""

#Task1a:
task_input=open("input1a.txt","r")
task_output=open("output1a.txt","w")
size= int(task_input.readline())

for i in range(size):
  temp= int(task_input.readline())
  if temp%2==0:
    print((f"{temp} is an Even number.\n"))
    task_output.write(f"{temp} is an Even number.\n")
  else:
    print(f"{temp} is an Odd number.\n")
    task_output.write(f"{temp} is an Odd number.\n")

task_input.close()
task_output.close()