# -*- coding: utf-8 -*-
"""task1b.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UmkVK0Xg1orrcGxLqicEDVC-9hXbE3IT
"""

#Task1b:
task_input = open("input1b.txt", "r")
size = int(task_input.readline())
task_output = open("output1b.txt", "w")

for i in range(size):
    temp_lst = task_input.readline().split()
    first = int(temp_lst[1])
    second = int(temp_lst[3])
    operator = temp_lst[2]

    if(operator == "+"):
        val = first + second
        print(f"The result of {first} {operator} {second} is {val}")
        task_output.write(f"The result of {first} {operator} {second} is {val}\n")

    elif(operator == "-"):
        val = first - second
        print(f"The result of {first} {operator} {second} is {val}")
        task_output.write(f"The result of {first} {operator} {second} is {val}\n")

    elif(operator == "*"):
        val = first * second
        print(f"The result of {first} {operator} {second} is {val}")
        task_output.write(f"The result of {first} {operator} {second} is {val}\n")

    else:
        val = first / second
        print(f"The result of {first} {operator} {second} is {val}")
        task_output.write(f"The result of {first} {operator} {second} is {val}\n")
task_input.close()
task_output.close()