# -*- coding: utf-8 -*-
"""task3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15WWMOCvmHckCnG4dT5gsRu6jkuF2_UOV
"""

#Task3:
def selectionSort(id_arr, mark_arr, size):
    for i in range(size - 1):
        max = i
        for j in range(i+1, size):
            if(mark_arr[j] > mark_arr[max]):
                max = j

            if(mark_arr[j] == mark_arr[max]):
                if(id_arr[j] < id_arr[max]):
                    max = j

        temp = mark_arr[max]
        mark_arr[max] = mark_arr[i]
        mark_arr[i] = temp

        temp = id_arr[max]
        id_arr[max] = id_arr[i]
        id_arr[i] = temp

task_input = open("input3.txt", "r")
task_output = open("output3.txt", "w")
size = int(task_input.readline())
id_arr = task_input.readline().split()
mark_arr = task_input.readline().split()
for i in range(size):
    id_arr[i] = int(id_arr[i])
    mark_arr[i] = int(mark_arr[i])

selectionSort(id_arr, mark_arr, size)
for i in range(size):
    print(f"ID: {id_arr[i]} Mark: {mark_arr[i]}")
    task_output.write(f"ID: {id_arr[i]} Mark: {mark_arr[i]}\n")

task_input.close()
task_output.close()