# -*- coding: utf-8 -*-
"""task2a.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Uqv9hfNNAsak6vN12H2tk5RWaa7qDh8H
"""

#task2a
#O(nlogn)
def merge(a,b):
  result=[]
  i=j=0
  while i< len(a) and j< len(b):
    if a[i]<= b[j]:
      result.append(a[i])
      i+=1
    else:
      result.append(b[j])
      j+=1
  result+=a[i:]
  result+=b[j:]
  return result

def mergeSort(arr):
  if len(arr) <= 1:
    return arr
  else:
    mid = len(arr)//2
    a = mergeSort(arr[:mid])
    b = mergeSort(arr[mid:])
    return merge(a,b)

inp=open("/content/input2a.txt","r")
out=open("/content/output2a.txt","w")
m = int(inp.readline())
temp1 = [int(x) for x in inp.readline().split()]
n = int(inp.readline())
temp2 = [int(x) for x in inp.readline().split()]

sort_arr1 = mergeSort(temp1)
sort_arr2 = mergeSort(temp2)
final_arr = merge(sort_arr1, sort_arr2)

s = ""
for i in range(m+n):
    s += str(final_arr[i]) + " "

#print(s)
out.write(s)

inp.close()
out.close()