# -*- coding: utf-8 -*-
"""task1a.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xI6vzD80JznQuSECnUxTGmyruBNJhWlA
"""

#task1a
#O(n**2)
inp= open("input1a.txt","r")
out= open("output1a.txt","w")

temp1 = [int(x) for x in inp.readline().split()]
temp2 = [int(x) for x in inp.readline().split()]

possible = False
for i in range(temp1[0]):
    for j in range(i+1, temp1[0]):
        if(temp2[i]+temp2[j] == temp1[1]):
            #print(i+1, j+1)
            out.write(f"{i+1} {j+1}")
            possible = True
            break
    if(possible):
        break
if(possible == False):
    #print("IMPOSSIBLE")
    out.write("IMPOSSIBLE")

inp.close()
out.close()

