# -*- coding: utf-8 -*-
"""task4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dt-QcUcayeZSJm3nVOkkdvH0iBpxxO8r
"""

#task4
#The time complexity of this code is O(logn)
def find_max(lst, i, j):
    if(abs(i-j) == 1 or abs(i-j) == 0):
        if(lst[i] >= lst[j]):
            return lst[i]
        else:
            return lst[j]
    else:
        mid = (i+j)//2
        right = find_max(lst, i, mid)
        left = find_max(lst, mid + 1, j)
        if(right >= left):
            return right
        else:
            return left

inp = open("/content/input4.txt", "r")
out = open("/content/output4.txt", "w")
size = int(inp.readline())
arr = [int(x) for x in inp.readline().split()]
val = find_max(arr, 0, size - 1)
#print(val)
out.write(str(val))
inp.close()
out.close()