# -*- coding: utf-8 -*-
"""task3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rgKWt0HZZ2fZiA76q7-nxUcFqA1lKvSm
"""

#task3
def merge(a,b):
  result=[]
  i=j=0
  while i< len(a) and j< len(b):
    if a[i]<= b[j]:
      result.append(a[i])
      i+=1
    else:
      result.append(b[j])
      j+=1
  result+=a[i:]
  result+=b[j:]
  return result

def mergeSort(arr):
    if len(arr) <= 1:
        return arr
    else:
        mid = len(arr)//2
        a = mergeSort(arr[:mid])
        b = mergeSort(arr[mid:])
        return merge(a,b)


inp=open("/content/input3.txt","r")
out=open("/content/output3.txt","w")
n=int(inp.readline())
arr=[int(x) for x in inp.readline().split()]
sort_arr = mergeSort(arr)
s = ""
for i in range(n):
    s += str(sort_arr[i]) + " "
#print(s)
out.write(s)
inp.close()
out.close()