# -*- coding: utf-8 -*-
"""task1b.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16nYNRh-DGT8fJZgjN5T6bPAsGun-ddvS
"""

#task1b
#O(n)
inp= open("input1b.txt","r")
out= open("output1b.txt","w")
line1= [int(x) for x in inp.readline().split()]
line2= [int(y) for y in inp.readline().split()]
sum=line1[1]
dict1 = {}
for i in range(len(line2)):
  if dict1.get(sum-line2[i])==None:
    dict1[line2[i]] = i+1
  else:
    out.write(f"{dict1.get(sum-line2[i])} {i + 1}\n")
    break
inp.close()
out.close()