# -*- coding: utf-8 -*-
"""Task-01(b).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MdF_JsR69yGNlriLZCpIEvkXtMiM70ww
"""

#task 1b
def adjacency_list(inp, out):
    n,m = inp.readline().split()
    n = int(n)
    m = int(m)
    temp = []
    for i in range(n + 1):
        temp.append([])
    for i in range(0, m):
        lst = [int(x) for x in inp.readline().split()]
        tup = (lst[1], lst[2])
        temp[lst[0]].append(tup)

    s = ""
    for i in range(len(temp)):
        if(len(temp[i]) == 0):
            s += str(i) + ": \n"
        else:
            s += str(i) + ": "
            for j in range(len(temp[i])):
                s += str(temp[i][j]) + " "

            s += "\n"

    print(s)
    out.write(s)

    inp.close()
    out.close()

inp = open("/content/input1b.txt", "r")
out = open("/content/output1b.txt", "w")
adjacency_list(inp, out)