# -*- coding: utf-8 -*-
"""Task-01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GppiftPqmbVjKPT-4zChLvnKeKimSwzJ
"""

#task 1
def adjacency_matrix(inp, out):
    n,m = inp.readline().split()
    n = int(n)
    m = int(m)
    matrix = []

    for i in range(n + 1):
        matrix.append([0] * (n+1))

    for i in range(m):
        lst = [int(x) for x in inp.readline().split()]
        matrix[lst[0]][lst[1]] = lst[2]
    s = ""
    for i in range(len(matrix)):
        for j in range(len(matrix[0])):
            s += str(matrix[i][j]) + " "
        s += "\n"
    print(s)
    out.write(s)

    inp.close()
    out.close()

inp = open("/content/input1.txt", "r")
out = open("/content/output1.txt", "w")
adjacency_matrix(inp, out)