# -*- coding: utf-8 -*-
"""task-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eeGWvSdBn6auUFWOfJ9hDkBeuzwZHXVp
"""

#task 1
def function(inp, out):
    n = int(inp.readline())
    time_arr = []
    for i in range(n):
        start, end = inp.readline().split()
        start = int(start)
        end = int(end)
        time_arr.append((end, start))

    time_arr.sort()
    # print(time_arr)
    maximize_task = []
    prev_end = 0
    for i in range(len(time_arr)):
        end = time_arr[i][0]
        start = time_arr[i][1]
        if(start >= prev_end):
            maximize_task.append((start, end))
            prev_end = end

    print(len(maximize_task), file = out)
    for i in maximize_task:
        print(i[0], i[1], file = out)

    inp.close()
    out.close()

inp = open("/content/input1.txt", "r")
out = open("/content/output1.txt", "w")
function(inp, out)